const ORIGINAL_GETLIST  = 'ORIGINAL_GETLIST';
const ORIGINAL_GETLIST_SUCCESS = 'ORIGINAL_GETLIST_SUCCESS';
const ORIGINAL_GETLIST_FAILURE = 'ORIGINAL_GETLIST_FAILURE';
const ORIGINAL_INSERT = 'ORIGINAL_INSERT';
const ORIGINAL_INSERT_SUCCESS = 'ORIGINAL_INSERT_SUCCESS';
const ORIGINAL_INSERT_FAILURE = 'ORIGINAL_INSERT_FAILURE';
const ORIGINAL_MODIFY = 'ORIGINAL_MODIFY';
const ORIGINAL_MODIFY_SUCCESS = 'ORIGINAL_MODIFY_SUCCESS';
const ORIGINAL_MODIFY_FAILURE = 'ORIGINAL_MODIFY_FAILURE';
const ORIGINAL_REMOVE = 'ORIGINAL_REMOVE';
const ORIGINAL_REMOVE_SUCCESS = 'ORIGINAL_REMOVE_SUCCESS';
const ORIGINAL_REMOVE_FAILURE = 'ORIGINAL_REMOVE_FAILURE';

export {
  ORIGINAL_GETLIST,
  ORIGINAL_GETLIST_SUCCESS,
  ORIGINAL_GETLIST_FAILURE,
  ORIGINAL_INSERT,
  ORIGINAL_INSERT_SUCCESS,
  ORIGINAL_INSERT_FAILURE,
  ORIGINAL_MODIFY,
  ORIGINAL_MODIFY_SUCCESS,
  ORIGINAL_MODIFY_FAILURE,
  ORIGINAL_REMOVE,
  ORIGINAL_REMOVE_SUCCESS,
  ORIGINAL_REMOVE_FAILURE,
};
