const ORIGINAL_GETLIST = 'ORIGINAL_GETLIST';
const ORIGINAL_GETLIST_SUCCESS = 'ORIGINAL_GETLIST_SUCCESS';
const ORIGINAL_GETLIST_FAILURE = 'ORIGINAL_GETLIST_FAILURE';
const ORIGINAL_BULKINSERT = 'ORIGINAL_BULKINSERT';
const ORIGINAL_BULKINSERT_SUCCESS = 'ORIGINAL_BULKINSERT_SUCCESS';
const ORIGINAL_BULKINSERT_FAILURE = 'ORIGINAL_BULKINSERT_FAILURE';
const ORIGINAL_INSERT = 'ORIGINAL_INSERT';
const ORIGINAL_INSERT_SUCCESS = 'ORIGINAL_INSERT_SUCCESS';
const ORIGINAL_INSERT_FAILURE = 'ORIGINAL_INSERT_FAILURE';
const ORIGINAL_MODIFY = 'ORIGINAL_MODIFY';
const ORIGINAL_MODIFY_SUCCESS = 'ORIGINAL_MODIFY_SUCCESS';
const ORIGINAL_MODIFY_FAILURE = 'ORIGINAL_MODIFY_FAILURE';
const ORIGINAL_REMOVE = 'ORIGINAL_REMOVE';
const ORIGINAL_REMOVE_SUCCESS = 'ORIGINAL_REMOVE_SUCCESS';
const ORIGINAL_REMOVE_FAILURE = 'ORIGINAL_REMOVE_FAILURE';
const ORIGINAL_REMOVEALL = 'ORIGINAL_REMOVEALL';
const ORIGINAL_REMOVEALL_SUCCESS = 'ORIGINAL_REMOVEALL_SUCCESS';
const ORIGINAL_REMOVEALL_FAILURE = 'ORIGINAL_REMOVEALL_FAILURE';
const VINTAGE_GETLIST = 'VINTAGE_GETLIST';
const VINTAGE_GETLIST_SUCCESS = 'VINTAGE_GETLIST_SUCCESS';
const VINTAGE_GETLIST_FAILURE = 'VINTAGE_GETLIST_FAILURE';
const VINTAGE_INSERT = 'VINTAGE_INSERT';
const VINTAGE_INSERT_SUCCESS = 'VINTAGE_INSERT_SUCCESS';
const VINTAGE_INSERT_FAILURE = 'VINTAGE_INSERT_FAILURE';
const VINTAGE_MODIFY = 'VINTAGE_MODIFY';
const VINTAGE_MODIFY_SUCCESS = 'VINTAGE_MODIFY_SUCCESS';
const VINTAGE_MODIFY_FAILURE = 'VINTAGE_MODIFY_FAILURE';
const VINTAGE_REMOVE = 'VINTAGE_REMOVE';
const VINTAGE_REMOVE_SUCCESS = 'VINTAGE_REMOVE_SUCCESS';
const VINTAGE_REMOVE_FAILURE = 'VINTAGE_REMOVE_FAILURE';
const VINTAGE_REMOVEALL = 'VINTAGE_REMOVEALL';
const VINTAGE_REMOVEALL_SUCCESS = 'VINTAGE_REMOVEALL_SUCCESS';
const VINTAGE_REMOVEALL_FAILURE = 'VINTAGE_REMOVEALL_FAILURE';
const SALE_GETLIST = 'SALE_GETLIST';
const SALE_GETLIST_SUCCESS = 'SALE_GETLIST_SUCCESS';
const SALE_GETLIST_FAILURE = 'SALE_GETLIST_FAILURE';
const SALE_INSERT = 'SALE_INSERT';
const SALE_INSERT_SUCCESS = 'SALE_INSERT_SUCCESS';
const SALE_INSERT_FAILURE = 'SALE_INSERT_FAILURE';
const SALE_BULKINSERT = 'SALE_BULKINSERT';
const SALE_BULKINSERT_SUCCESS = 'SALE_BULKINSERT_SUCCESS';
const SALE_BULKINSERT_FAILURE = 'SALE_BULKINSERT_FAILURE';
const SALE_MODIFY = 'SALE_MODIFY';
const SALE_MODIFY_SUCCESS = 'SALE_MODIFY_SUCCESS';
const SALE_MODIFY_FAILURE = 'SALE_MODIFY_FAILURE';
const SALE_BULKMODIFY = 'SALE_BULKMODIFY';
const SALE_BULKMODIFY_SUCCESS = 'SALE_BULKMODIFY_SUCCESS';
const SALE_BULKMODIFY_FAILURE = 'SALE_BULKMODIFY_FAILURE';
const SALE_REMOVE = 'SALE_REMOVE';
const SALE_REMOVE_SUCCESS = 'SALE_REMOVE_SUCCESS';
const SALE_REMOVE_FAILURE = 'SALE_REMOVE_FAILURE';
const SALE_BULKREMOVE = 'SALE_BULKREMOVE';
const SALE_BULKREMOVE_SUCCESS = 'SALE_BULKREMOVE_SUCCESS';
const SALE_BULKREMOVE_FAILURE = 'SALE_BULKREMOVE_FAILURE';
const SALE_REMOVEALL = 'SALE_REMOVEALL';
const SALE_REMOVEALL_SUCCESS = 'SALE_REMOVEALL_SUCCESS';
const SALE_REMOVEALL_FAILURE = 'SALE_REMOVEALL_FAILURE';
const ACCOUNT_LOGIN = 'ACCOUNT_LOGIN';
const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
const ACCOUNT_LOGIN_FAILURE = 'ACCOUNT_LOGIN_FAILURE';
const ACCOUNT_SESSION = 'ACCOUNT_SESSION';
const ACCOUNT_SESSION_SUCCESS = 'ACCOUNT_SESSION_SUCCESS';
const ACCOUNT_SESSION_FAILURE = 'ACCOUNT_SESSION_FAILURE';
const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';
const ACCOUNT_LOGOUT_SUCCESS = 'ACCOUNT_LOGOUT_SUCCESS';
const ACCOUNT_LOGOUT_FAILURE = 'ACCOUNT_LOGOUT_FAILURE';
const ACCOUNT_GETLIST = 'ACCOUNT_GETLIST';
const ACCOUNT_GETLIST_SUCCESS = 'ACCOUNT_GETLIST_SUCCESS';
const ACCOUNT_GETLIST_FAILURE = 'ACCOUNT_GETLIST_FAILURE';
const ACCOUNT_INSERT = 'ACCOUNT_INSERT';
const ACCOUNT_INSERT_SUCCESS = 'ACCOUNT_INSERT_SUCCESS';
const ACCOUNT_INSERT_FAILURE = 'ACCOUNT_INSERT_FAILURE';
const ACCOUNT_MODIFY = 'ACCOUNT_MODIFY';
const ACCOUNT_MODIFY_SUCCESS = 'ACCOUNT_MODIFY_SUCCESS';
const ACCOUNT_MODIFY_FAILURE = 'ACCOUNT_MODIFY_FAILURE';
const ACCOUNT_REMOVE = 'ACCOUNT_REMOVE';
const ACCOUNT_REMOVE_SUCCESS = 'ACCOUNT_REMOVE_SUCCESS';
const ACCOUNT_REMOVE_FAILURE = 'ACCOUNT_REMOVE_FAILURE';
const ACCOUNT_REMOVEALL = 'ACCOUNT_REMOVEALL';
const ACCOUNT_REMOVEALL_SUCCESS = 'ACCOUNT_REMOVEALL_SUCCESS';
const ACCOUNT_REMOVEALL_FAILURE = 'ACCOUNT_REMOVEALL_FAILURE';
const CUSTOMERACCOUNT_LOGIN = 'CUSTOMERACCOUNT_LOGIN';
const CUSTOMERACCOUNT_LOGIN_SUCCESS = 'CUSTOMERACCOUNT_LOGIN_SUCCESS';
const CUSTOMERACCOUNT_LOGIN_FAILURE = 'CUSTOMERACCOUNT_LOGIN_FAILURE';
const CUSTOMERACCOUNT_SESSION = 'CUSTOMERACCOUNT_SESSION';
const CUSTOMERACCOUNT_SESSION_SUCCESS = 'CUSTOMERACCOUNT_SESSION_SUCCESS';
const CUSTOMERACCOUNT_SESSION_FAILURE = 'CUSTOMERACCOUNT_SESSION_FAILURE';
const CUSTOMERACCOUNT_LOGOUT = 'CUSTOMERACCOUNT_LOGOUT';
const CUSTOMERACCOUNT_LOGOUT_SUCCESS = 'CUSTOMERACCOUNT_LOGOUT_SUCCESS';
const CUSTOMERACCOUNT_LOGOUT_FAILURE = 'CUSTOMERACCOUNT_LOGOUT_FAILURE';
const SHOP_GETLIST = 'SHOP_GETLIST';
const SHOP_GETLIST_SUCCESS = 'SHOP_GETLIST_SUCCESS';
const SHOP_GETLIST_FAILURE = 'SHOP_GETLIST_FAILURE';
const SHOP_INSERT = 'SHOP_INSERT';
const SHOP_INSERT_SUCCESS = 'SHOP_INSERT_SUCCESS';
const SHOP_INSERT_FAILURE = 'SHOP_INSERT_FAILURE';
const SHOP_MODIFY = 'SHOP_MODIFY';
const SHOP_MODIFY_SUCCESS = 'SHOP_MODIFY_SUCCESS';
const SHOP_MODIFY_FAILURE = 'SHOP_MODIFY_FAILURE';
const SHOP_REMOVE = 'SHOP_REMOVE';
const SHOP_REMOVE_SUCCESS = 'SHOP_REMOVE_SUCCESS';
const SHOP_REMOVE_FAILURE = 'SHOP_REMOVE_FAILURE';
const SHOP_REMOVEALL = 'SHOP_REMOVEALL';
const SHOP_REMOVEALL_SUCCESS = 'SHOP_REMOVEALL_SUCCESS';
const SHOP_REMOVEALL_FAILURE = 'SHOP_REMOVEALL_FAILURE';
const CUSTOMER_GETLIST = 'CUSTOMER_GETLIST';
const CUSTOMER_GETLIST_SUCCESS = 'CUSTOMER_GETLIST_SUCCESS';
const CUSTOMER_GETLIST_FAILURE = 'CUSTOMER_GETLIST_FAILURE';
const CUSTOMER_INSERT = 'CUSTOMER_INSERT';
const CUSTOMER_INSERT_SUCCESS = 'CUSTOMER_INSERT_SUCCESS';
const CUSTOMER_INSERT_FAILURE = 'CUSTOMER_INSERT_FAILURE';
const CUSTOMER_MODIFY = 'CUSTOMER_MODIFY';
const CUSTOMER_MODIFY_SUCCESS = 'CUSTOMER_MODIFY_SUCCESS';
const CUSTOMER_MODIFY_FAILURE = 'CUSTOMER_MODIFY_FAILURE';
const CUSTOMER_REMOVE = 'CUSTOMER_REMOVE';
const CUSTOMER_REMOVE_SUCCESS = 'CUSTOMER_REMOVE_SUCCESS';
const CUSTOMER_REMOVE_FAILURE = 'CUSTOMER_REMOVE_FAILURE';
const CUSTOMER_REMOVEALL = 'CUSTOMER_REMOVEALL';
const CUSTOMER_REMOVEALL_SUCCESS = 'CUSTOMER_REMOVEALL_SUCCESS';
const CUSTOMER_REMOVEALL_FAILURE = 'CUSTOMER_REMOVEALL_FAILURE';
const CUSTOMERBASE_PRELOGIN = 'CUSTOMERBASE_PRELOGIN';
const CUSTOMERBASE_PRELOGIN_SUCCESS = 'CUSTOMERBASE_PRELOGIN_SUCCESS';
const CUSTOMERBASE_PRELOGIN_FAILURE = 'CUSTOMERBASE_PRELOGIN_FAILURE';
const CUSTOMERBASE_GETLIST = 'CUSTOMERBASE_GETLIST';
const CUSTOMERBASE_GETLIST_SUCCESS = 'CUSTOMERBASE_GETLIST_SUCCESS';
const CUSTOMERBASE_GETLIST_FAILURE = 'CUSTOMERBASE_GETLIST_FAILURE';
const CUSTOMERBASE_INSERT = 'CUSTOMERBASE_INSERT';
const CUSTOMERBASE_INSERT_SUCCESS = 'CUSTOMERBASE_INSERT_SUCCESS';
const CUSTOMERBASE_INSERT_FAILURE = 'CUSTOMERBASE_INSERT_FAILURE';
const CUSTOMERBASE_MODIFY = 'CUSTOMERBASE_MODIFY';
const CUSTOMERBASE_MODIFY_SUCCESS = 'CUSTOMERBASE_MODIFY_SUCCESS';
const CUSTOMERBASE_MODIFY_FAILURE = 'CUSTOMERBASE_MODIFY_FAILURE';
const CUSTOMERBASE_REMOVE = 'CUSTOMERBASE_REMOVE';
const CUSTOMERBASE_REMOVE_SUCCESS = 'CUSTOMERBASE_REMOVE_SUCCESS';
const CUSTOMERBASE_REMOVE_FAILURE = 'CUSTOMERBASE_REMOVE_FAILURE';
const CUSTOMERBASE_REMOVEALL = 'CUSTOMERBASE_REMOVEALL';
const CUSTOMERBASE_REMOVEALL_SUCCESS = 'CUSTOMERBASE_REMOVEALL_SUCCESS';
const CUSTOMERBASE_REMOVEALL_FAILURE = 'CUSTOMERBASE_REMOVEALL_FAILURE';
const CUSTOMERBASE_GETSTORE = 'CUSTOMERBASE_GETSTORE';
const CUSTOMERBASE_GETSTORE_SUCCESS = 'CUSTOMERBASE_GETSTORE_SUCCESS';
const CUSTOMERBASE_GETSTORE_FAILURE = 'CUSTOMERBASE_GETSTORE_FAILURE';
const CUSTOMERBASE_GETHISTORY = 'CUSTOMERBASE_GETHISTORY';
const CUSTOMERBASE_GETHISTORY_SUCCESS = 'CUSTOMERBASE_GETHISTORY_SUCCESS';
const CUSTOMERBASE_GETHISTORY_FAILURE = 'CUSTOMERBASE_GETHISTORY_FAILURE';
const CUSTOMERBASE_FINDPASSWORD = 'CUSTOMERBASE_FINDPASSWORD';
const CUSTOMERBASE_FINDPASSWORD_SUCCESS = 'CUSTOMERBASE_FINDPASSWORD_SUCCESS';
const CUSTOMERBASE_FINDPASSWORD_FAILURE = 'CUSTOMERBASE_FINDPASSWORD_FAILURE';
const STORE_GETLIST = 'STORE_GETLIST';
const STORE_GETLIST_SUCCESS = 'STORE_GETLIST_SUCCESS';
const STORE_GETLIST_FAILURE = 'STORE_GETLIST_FAILURE';
const STORE_INSERT = 'STORE_INSERT';
const STORE_INSERT_SUCCESS = 'STORE_INSERT_SUCCESS';
const STORE_INSERT_FAILURE = 'STORE_INSERT_FAILURE';
const STORE_BULKINSERT = 'STORE_BULKINSERT';
const STORE_BULKINSERT_SUCCESS = 'STORE_BULKINSERT_SUCCESS';
const STORE_BULKINSERT_FAILURE = 'STORE_BULKINSERT_FAILURE';
const STORE_REMOVEALL = 'STORE_REMOVEALL';
const STORE_REMOVEALL_SUCCESS = 'STORE_REMOVEALL_SUCCESS';
const STORE_REMOVEALL_FAILURE = 'STORE_REMOVEALL_FAILURE';
const GRAPE_GETLIST = 'GRAPE_GETLIST';
const GRAPE_GETLIST_SUCCESS = 'GRAPE_GETLIST_SUCCESS';
const GRAPE_GETLIST_FAILURE = 'GRAPE_GETLIST_FAILURE';
const GRAPE_INSERT = 'GRAPE_INSERT';
const GRAPE_INSERT_SUCCESS = 'GRAPE_INSERT_SUCCESS';
const GRAPE_INSERT_FAILURE = 'GRAPE_INSERT_FAILURE';
const GRAPE_REMOVE = 'GRAPE_REMOVE';
const GRAPE_REMOVE_SUCCESS = 'GRAPE_REMOVE_SUCCESS';
const GRAPE_REMOVE_FAILURE = 'GRAPE_REMOVE_FAILURE';
const GRAPE_REMOVEALL = 'GRAPE_REMOVEALL';
const GRAPE_REMOVEALL_SUCCESS = 'GRAPE_REMOVEALL_SUCCESS';
const GRAPE_REMOVEALL_FAILURE = 'GRAPE_REMOVEALL_FAILURE';
const LOCATION_GETLIST = 'LOCATION_GETLIST';
const LOCATION_GETLIST_SUCCESS = 'LOCATION_GETLIST_SUCCESS';
const LOCATION_GETLIST_FAILURE = 'LOCATION_GETLIST_FAILURE';
const LOCATION_INSERT = 'LOCATION_INSERT';
const LOCATION_INSERT_SUCCESS = 'LOCATION_INSERT_SUCCESS';
const LOCATION_INSERT_FAILURE = 'LOCATION_INSERT_FAILURE';
const LOCATION_REMOVE = 'LOCATION_REMOVE';
const LOCATION_REMOVE_SUCCESS = 'LOCATION_REMOVE_SUCCESS';
const LOCATION_REMOVE_FAILURE = 'LOCATION_REMOVE_FAILURE';
const LOCATION_REMOVEALL = 'LOCATION_REMOVEALL';
const LOCATION_REMOVEALL_SUCCESS = 'LOCATION_REMOVEALL_SUCCESS';
const LOCATION_REMOVEALL_FAILURE = 'LOCATION_REMOVEALL_FAILURE';
const EXCEL_TABLETOEXCEL = 'EXCEL_TABLETOEXCEL';
const EXCEL_TABLETOEXCEL_SUCCESS = 'EXCEL_TABLETOEXCEL_SUCCESS';
const EXCEL_TABLETOEXCEL_FAILURE = 'EXCEL_TABLETOEXCEL_FAILURE';
const EXCEL_EXCELTOTABLE = 'EXCEL_EXCELTOTABLE';
const EXCEL_EXCELTOTABLE_SUCCESS = 'EXCEL_EXCELTOTABLE_SUCCESS';
const EXCEL_EXCELTOTABLE_FAILURE = 'EXCEL_EXCELTOTABLE_FAILURE';
const CONFIGURATION_GET = 'CONFIGURATION_GET';
const CONFIGURATION_GET_SUCCESS = 'CONFIGURATION_GET_SUCCESS';
const CONFIGURATION_GET_FAILURE = 'CONFIGURATION_GET_FAILURE';
const CONFIGURATION_MODIFY = 'CONFIGURATION_MODIFY';
const CONFIGURATION_MODIFY_SUCCESS = 'CONFIGURATION_MODIFY_SUCCESS';
const CONFIGURATION_MODIFY_FAILURE = 'CONFIGURATION_MODIFY_FAILURE';

export {
  ORIGINAL_GETLIST,
  ORIGINAL_GETLIST_SUCCESS,
  ORIGINAL_GETLIST_FAILURE,
  ORIGINAL_BULKINSERT,
  ORIGINAL_BULKINSERT_SUCCESS,
  ORIGINAL_BULKINSERT_FAILURE,
  ORIGINAL_INSERT,
  ORIGINAL_INSERT_SUCCESS,
  ORIGINAL_INSERT_FAILURE,
  ORIGINAL_MODIFY,
  ORIGINAL_MODIFY_SUCCESS,
  ORIGINAL_MODIFY_FAILURE,
  ORIGINAL_REMOVE,
  ORIGINAL_REMOVE_SUCCESS,
  ORIGINAL_REMOVE_FAILURE,
  ORIGINAL_REMOVEALL,
  ORIGINAL_REMOVEALL_SUCCESS,
  ORIGINAL_REMOVEALL_FAILURE,
  VINTAGE_GETLIST,
  VINTAGE_GETLIST_SUCCESS,
  VINTAGE_GETLIST_FAILURE,
  VINTAGE_INSERT,
  VINTAGE_INSERT_SUCCESS,
  VINTAGE_INSERT_FAILURE,
  VINTAGE_MODIFY,
  VINTAGE_MODIFY_SUCCESS,
  VINTAGE_MODIFY_FAILURE,
  VINTAGE_REMOVE,
  VINTAGE_REMOVE_SUCCESS,
  VINTAGE_REMOVE_FAILURE,
  VINTAGE_REMOVEALL,
  VINTAGE_REMOVEALL_SUCCESS,
  VINTAGE_REMOVEALL_FAILURE,
  SALE_GETLIST,
  SALE_GETLIST_SUCCESS,
  SALE_GETLIST_FAILURE,
  SALE_INSERT,
  SALE_INSERT_SUCCESS,
  SALE_INSERT_FAILURE,
  SALE_BULKINSERT,
  SALE_BULKINSERT_SUCCESS,
  SALE_BULKINSERT_FAILURE,
  SALE_MODIFY,
  SALE_MODIFY_SUCCESS,
  SALE_MODIFY_FAILURE,
  SALE_BULKMODIFY,
  SALE_BULKMODIFY_SUCCESS,
  SALE_BULKMODIFY_FAILURE,
  SALE_REMOVE,
  SALE_REMOVE_SUCCESS,
  SALE_REMOVE_FAILURE,
  SALE_BULKREMOVE,
  SALE_BULKREMOVE_SUCCESS,
  SALE_BULKREMOVE_FAILURE,
  SALE_REMOVEALL,
  SALE_REMOVEALL_SUCCESS,
  SALE_REMOVEALL_FAILURE,
  ACCOUNT_LOGIN,
  ACCOUNT_LOGIN_SUCCESS,
  ACCOUNT_LOGIN_FAILURE,
  ACCOUNT_SESSION,
  ACCOUNT_SESSION_SUCCESS,
  ACCOUNT_SESSION_FAILURE,
  ACCOUNT_LOGOUT,
  ACCOUNT_LOGOUT_SUCCESS,
  ACCOUNT_LOGOUT_FAILURE,
  ACCOUNT_GETLIST,
  ACCOUNT_GETLIST_SUCCESS,
  ACCOUNT_GETLIST_FAILURE,
  ACCOUNT_INSERT,
  ACCOUNT_INSERT_SUCCESS,
  ACCOUNT_INSERT_FAILURE,
  ACCOUNT_MODIFY,
  ACCOUNT_MODIFY_SUCCESS,
  ACCOUNT_MODIFY_FAILURE,
  ACCOUNT_REMOVE,
  ACCOUNT_REMOVE_SUCCESS,
  ACCOUNT_REMOVE_FAILURE,
  ACCOUNT_REMOVEALL,
  ACCOUNT_REMOVEALL_SUCCESS,
  ACCOUNT_REMOVEALL_FAILURE,
  CUSTOMERACCOUNT_LOGIN,
  CUSTOMERACCOUNT_LOGIN_SUCCESS,
  CUSTOMERACCOUNT_LOGIN_FAILURE,
  CUSTOMERACCOUNT_SESSION,
  CUSTOMERACCOUNT_SESSION_SUCCESS,
  CUSTOMERACCOUNT_SESSION_FAILURE,
  CUSTOMERACCOUNT_LOGOUT,
  CUSTOMERACCOUNT_LOGOUT_SUCCESS,
  CUSTOMERACCOUNT_LOGOUT_FAILURE,
  SHOP_GETLIST,
  SHOP_GETLIST_SUCCESS,
  SHOP_GETLIST_FAILURE,
  SHOP_INSERT,
  SHOP_INSERT_SUCCESS,
  SHOP_INSERT_FAILURE,
  SHOP_MODIFY,
  SHOP_MODIFY_SUCCESS,
  SHOP_MODIFY_FAILURE,
  SHOP_REMOVE,
  SHOP_REMOVE_SUCCESS,
  SHOP_REMOVE_FAILURE,
  SHOP_REMOVEALL,
  SHOP_REMOVEALL_SUCCESS,
  SHOP_REMOVEALL_FAILURE,
  CUSTOMER_GETLIST,
  CUSTOMER_GETLIST_SUCCESS,
  CUSTOMER_GETLIST_FAILURE,
  CUSTOMER_INSERT,
  CUSTOMER_INSERT_SUCCESS,
  CUSTOMER_INSERT_FAILURE,
  CUSTOMER_MODIFY,
  CUSTOMER_MODIFY_SUCCESS,
  CUSTOMER_MODIFY_FAILURE,
  CUSTOMER_REMOVE,
  CUSTOMER_REMOVE_SUCCESS,
  CUSTOMER_REMOVE_FAILURE,
  CUSTOMER_REMOVEALL,
  CUSTOMER_REMOVEALL_SUCCESS,
  CUSTOMER_REMOVEALL_FAILURE,
  CUSTOMERBASE_PRELOGIN,
  CUSTOMERBASE_PRELOGIN_SUCCESS,
  CUSTOMERBASE_PRELOGIN_FAILURE,
  CUSTOMERBASE_GETLIST,
  CUSTOMERBASE_GETLIST_SUCCESS,
  CUSTOMERBASE_GETLIST_FAILURE,
  CUSTOMERBASE_INSERT,
  CUSTOMERBASE_INSERT_SUCCESS,
  CUSTOMERBASE_INSERT_FAILURE,
  CUSTOMERBASE_MODIFY,
  CUSTOMERBASE_MODIFY_SUCCESS,
  CUSTOMERBASE_MODIFY_FAILURE,
  CUSTOMERBASE_REMOVE,
  CUSTOMERBASE_REMOVE_SUCCESS,
  CUSTOMERBASE_REMOVE_FAILURE,
  CUSTOMERBASE_REMOVEALL,
  CUSTOMERBASE_REMOVEALL_SUCCESS,
  CUSTOMERBASE_REMOVEALL_FAILURE,
  CUSTOMERBASE_GETSTORE,
  CUSTOMERBASE_GETSTORE_SUCCESS,
  CUSTOMERBASE_GETSTORE_FAILURE,
  CUSTOMERBASE_GETHISTORY,
  CUSTOMERBASE_GETHISTORY_SUCCESS,
  CUSTOMERBASE_GETHISTORY_FAILURE,
  CUSTOMERBASE_FINDPASSWORD,
  CUSTOMERBASE_FINDPASSWORD_SUCCESS,
  CUSTOMERBASE_FINDPASSWORD_FAILURE,
  STORE_GETLIST,
  STORE_GETLIST_SUCCESS,
  STORE_GETLIST_FAILURE,
  STORE_INSERT,
  STORE_INSERT_SUCCESS,
  STORE_INSERT_FAILURE,
  STORE_BULKINSERT,
  STORE_BULKINSERT_SUCCESS,
  STORE_BULKINSERT_FAILURE,
  STORE_REMOVEALL,
  STORE_REMOVEALL_SUCCESS,
  STORE_REMOVEALL_FAILURE,
  GRAPE_GETLIST,
  GRAPE_GETLIST_SUCCESS,
  GRAPE_GETLIST_FAILURE,
  GRAPE_INSERT,
  GRAPE_INSERT_SUCCESS,
  GRAPE_INSERT_FAILURE,
  GRAPE_REMOVE,
  GRAPE_REMOVE_SUCCESS,
  GRAPE_REMOVE_FAILURE,
  GRAPE_REMOVEALL,
  GRAPE_REMOVEALL_SUCCESS,
  GRAPE_REMOVEALL_FAILURE,
  LOCATION_GETLIST,
  LOCATION_GETLIST_SUCCESS,
  LOCATION_GETLIST_FAILURE,
  LOCATION_INSERT,
  LOCATION_INSERT_SUCCESS,
  LOCATION_INSERT_FAILURE,
  LOCATION_REMOVE,
  LOCATION_REMOVE_SUCCESS,
  LOCATION_REMOVE_FAILURE,
  LOCATION_REMOVEALL,
  LOCATION_REMOVEALL_SUCCESS,
  LOCATION_REMOVEALL_FAILURE,
  EXCEL_TABLETOEXCEL,
  EXCEL_TABLETOEXCEL_SUCCESS,
  EXCEL_TABLETOEXCEL_FAILURE,
  EXCEL_EXCELTOTABLE,
  EXCEL_EXCELTOTABLE_SUCCESS,
  EXCEL_EXCELTOTABLE_FAILURE,
  CONFIGURATION_GET,
  CONFIGURATION_GET_SUCCESS,
  CONFIGURATION_GET_FAILURE,
  CONFIGURATION_MODIFY,
  CONFIGURATION_MODIFY_SUCCESS,
  CONFIGURATION_MODIFY_FAILURE,
};
